// examples/react/src/main.tsx
import ReactDOM from 'react-dom/client';
import App from './App';
import { globalStyle } from '@macaron-css/core';
import { StrictMode } from 'react';

globalStyle('*', {
  padding: 0,
  margin: 0,
  boxSizing: 'border-box',
});

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <StrictMode>
    <App />
  </StrictMode>
);

// playground/src/index.tsx
import './globals';

/* @refresh reload */
import { render } from 'solid-js/web';
import { globalStyle } from '@macaron-css/core';

import App from './App';

globalStyle('*', {
  boxSizing: 'border-box',
  margin: 0,
  padding: 0,
});

render(() => <App />, document.getElementById('root') as HTMLElement);
